import { TestCase } from './types';

export const testCases: TestCase[] = [
  // Поиск товаров
  {
    id: 'find-1',
    name: 'Поиск по названию',
    category: 'Поиск',
    message: 'Найди парацетамол',
    description: 'FIND_PRODUCT_BY_NAME',
  },
  {
    id: 'find-2',
    name: 'Поиск по симптому',
    category: 'Поиск',
    message: 'У меня болит голова, что посоветуете?',
    description: 'FIND_BY_SYMPTOM',
  },
  {
    id: 'find-3',
    name: 'Поиск аналогов',
    category: 'Поиск',
    message: 'Есть аналоги Нурофена подешевле?',
    description: 'FIND_ANALOGS',
  },
  {
    id: 'find-4',
    name: 'Поиск по болезни',
    category: 'Поиск',
    message: 'Что принять при простуде?',
    description: 'FIND_BY_DISEASE',
  },
  {
    id: 'find-5',
    name: 'С фильтрами',
    category: 'Поиск',
    message: 'Покажи детские сиропы от кашля без сахара',
    description: 'FIND_BY_META_FILTERS',
  },
  {
    id: 'find-6',
    name: 'Поиск по МНН',
    category: 'Поиск',
    message: 'Найди препараты с ибупрофеном',
    description: 'FIND_PRODUCT_BY_INN',
  },
  {
    id: 'find-7',
    name: 'От живота',
    category: 'Поиск',
    message: 'Что-нибудь от живота',
    description: 'FIND_BY_SYMPTOM - желудок/диарея',
  },
  {
    id: 'find-8',
    name: 'От аллергии',
    category: 'Поиск',
    message: 'Нужно средство от аллергии',
    description: 'FIND_BY_SYMPTOM - аллергия',
  },

  // Корзина
  {
    id: 'cart-1',
    name: 'Показать корзину',
    category: 'Корзина',
    message: 'Что у меня в корзине?',
    description: 'SHOW_CART (есть 2 товара)',
    user_id: 'test-user-123',
  },
  {
    id: 'cart-2',
    name: 'Добавить в корзину',
    category: 'Корзина',
    message: 'Добавь нурофен в корзину',
    description: 'ADD_TO_CART',
    user_id: 'test-user-123',
  },
  {
    id: 'cart-3',
    name: 'Удалить из корзины',
    category: 'Корзина',
    message: 'Убери аспирин из корзины',
    description: 'REMOVE_FROM_CART',
    user_id: 'test-user-123',
  },
  {
    id: 'cart-4',
    name: 'Очистить корзину',
    category: 'Корзина',
    message: 'Очисти корзину',
    description: 'CLEAR_CART',
    user_id: 'test-user-123',
  },
  {
    id: 'cart-5',
    name: 'Пустая корзина',
    category: 'Корзина',
    message: 'Покажи корзину',
    description: 'SHOW_CART (пустая)',
    user_id: 'default',
  },

  // Заказы
  {
    id: 'order-1',
    name: 'История заказов',
    category: 'Заказы',
    message: 'Покажи мои заказы',
    description: 'SHOW_ORDER_HISTORY (6 заказов)',
    user_id: 'test-user-123',
  },
  {
    id: 'order-2',
    name: 'Статус заказа',
    category: 'Заказы',
    message: 'Где мой заказ 12345?',
    description: 'SHOW_ORDER_STATUS',
    user_id: 'test-user-123',
  },
  {
    id: 'order-3',
    name: 'Активные заказы',
    category: 'Заказы',
    message: 'Какие заказы сейчас в обработке?',
    description: 'SHOW_ACTIVE_ORDERS (2 активных)',
    user_id: 'test-user-123',
  },
  {
    id: 'order-4',
    name: 'Отмена заказа',
    category: 'Заказы',
    message: 'Хочу отменить последний заказ',
    description: 'CANCEL_ORDER',
    user_id: 'test-user-123',
  },
  {
    id: 'order-5',
    name: 'Готовые к выдаче',
    category: 'Заказы',
    message: 'Какие заказы готовы к выдаче?',
    description: 'Заказ 67890 готов, код: 4527',
    user_id: 'test-user-123',
  },

  // Профиль
  {
    id: 'profile-1',
    name: 'Мой профиль',
    category: 'Профиль',
    message: 'Открой мой профиль',
    description: 'SHOW_PROFILE',
    user_id: 'test-user-123',
  },
  {
    id: 'profile-2',
    name: 'Избранное',
    category: 'Профиль',
    message: 'Покажи избранные товары',
    description: 'SHOW_FAVORITES (5 товаров)',
    user_id: 'test-user-123',
  },
  {
    id: 'profile-3',
    name: 'Баланс бонусов',
    category: 'Профиль',
    message: 'Сколько у меня бонусов?',
    description: 'SHOW_BONUS_BALANCE (2500 бонусов)',
    user_id: 'test-user-123',
  },
  {
    id: 'profile-4',
    name: 'Мои адреса',
    category: 'Профиль',
    message: 'Покажи мои адреса доставки',
    description: 'Показать адреса (3 адреса)',
    user_id: 'test-user-123',
  },

  // Аптеки
  {
    id: 'pharmacy-1',
    name: 'Ближайшие аптеки',
    category: 'Аптеки',
    message: 'Где ближайшая аптека?',
    description: 'SHOW_NEARBY_PHARMACIES',
  },
  {
    id: 'pharmacy-2',
    name: 'Аптеки у метро',
    category: 'Аптеки',
    message: 'Есть аптеки рядом с метро Курская?',
    description: 'SHOW_PHARMACIES_BY_METRO - Аптека №456',
  },
  {
    id: 'pharmacy-3',
    name: 'Наличие в аптеке',
    category: 'Аптеки',
    message: 'Есть ли Аспирин в аптеке на Тверской?',
    description: 'SHOW_PHARMACY_AVAILABILITY',
  },
  {
    id: 'pharmacy-4',
    name: 'Круглосуточные аптеки',
    category: 'Аптеки',
    message: 'Какие аптеки работают круглосуточно?',
    description: 'Аптеки №456 (Курская) и №999 (Парк культуры)',
  },

  // Информация
  {
    id: 'info-1',
    name: 'Правила возврата',
    category: 'Информация',
    message: 'Как вернуть лекарство?',
    description: 'RETURN_POLICY',
  },
  {
    id: 'info-2',
    name: 'Доставка',
    category: 'Информация',
    message: 'Как работает доставка?',
    description: 'DELIVERY_RULES',
  },
  {
    id: 'info-3',
    name: 'Рецептурные препараты',
    category: 'Информация',
    message: 'Можно ли купить антибиотики без рецепта?',
    description: 'PRESCRIPTION_POLICY',
  },
  {
    id: 'info-4',
    name: 'Инструкция препарата',
    category: 'Информация',
    message: 'Как принимать парацетамол?',
    description: 'SHOW_PRODUCT_INSTRUCTIONS',
  },
  {
    id: 'info-5',
    name: 'Противопоказания',
    category: 'Информация',
    message: 'Какие противопоказания у Нурофена?',
    description: 'SHOW_PRODUCT_CONTRAINDICATIONS',
  },

  // Small talk
  {
    id: 'talk-1',
    name: 'Приветствие',
    category: 'Общение',
    message: 'Привет!',
    description: 'SMALL_TALK',
  },
  {
    id: 'talk-2',
    name: 'Что умеешь?',
    category: 'Общение',
    message: 'Что ты умеешь делать?',
    description: 'SMALL_TALK',
  },
  {
    id: 'talk-3',
    name: 'Непонятный запрос',
    category: 'Общение',
    message: 'агкшгаршл ывлоа рывоа',
    description: 'UNKNOWN',
  },
  {
    id: 'talk-4',
    name: 'Благодарность',
    category: 'Общение',
    message: 'Спасибо за помощь!',
    description: 'SMALL_TALK',
  },

  // Сложные сценарии
  {
    id: 'complex-1',
    name: 'Многоинтент',
    category: 'Сложные',
    message: 'Найди капли для глаз и добавь их в корзину',
    description: 'Комбинация FIND + ADD_TO_CART',
    user_id: 'test-user-123',
  },
  {
    id: 'complex-2',
    name: 'Уточняющие вопросы',
    category: 'Сложные',
    message: 'Мне нужно что-то от живота',
    description: 'Слот-филлинг: тип боли, возраст',
  },
  {
    id: 'complex-3',
    name: 'Контекстный запрос',
    category: 'Сложные',
    message: 'А подешевле есть?',
    description: 'Требует контекст предыдущего запроса',
  },
  {
    id: 'complex-4',
    name: 'Для мамы с детьми',
    category: 'Сложные',
    message: 'Покажи мои заказы',
    description: 'user-mother: заказ в доставке',
    user_id: 'user-mother',
  },
  {
    id: 'complex-5',
    name: 'Для пожилого',
    category: 'Сложные',
    message: 'Какие заказы готовы забрать?',
    description: 'user-elderly: заказ готов, код 7891',
    user_id: 'user-elderly',
  },

  // Особые случаи
  {
    id: 'special-1',
    name: 'Рецептурный препарат',
    category: 'Особые',
    message: 'Найди амоксициллин',
    description: 'Rx препарат - требуется рецепт',
  },
  {
    id: 'special-2',
    name: 'Нет в наличии',
    category: 'Особые',
    message: 'Есть спрей от насморка?',
    description: 'Товар out_of_stock',
  },
  {
    id: 'special-3',
    name: 'Для ребёнка',
    category: 'Особые',
    message: 'Что дать ребёнку 5 лет от кашля?',
    description: 'Детский сироп - is_for_children: true',
  },
];

export const testCaseCategories = [...new Set(testCases.map(tc => tc.category))];
